### ISSUE TITLE
menuItem() function

### ISSUE THREAD

**Issue by dburguer** [trafficonese/leaflet.extras2#10]
The new menuItem() function causes me a problem with other packages, such as shiny or shinydashboards. If it were possible to change the name of the function in future versions

**Comment by trafficonese** [comment]
Indeed, there are multiple functions with that name. I haven't thought of it when including that plugin. I will change the function name and deprecate the current function. Do you have an idea for a better name?

**Comment by dburguer** [comment]
it could be layermenuItems() or you can put the package name at the beginning extras2.menuItem(). That occurs to me now haha. Thanks for the reply!!

**Comment by trafficonese** [comment]
The functions `menuItem, mapmenuItems, markermenuItems` are now deprecated and are replaced with:
`context_menuItem, context_mapmenuItems, context_markermenuItems`
