### ISSUE TITLE
Processing data for addVelocity

### ISSUE THREAD

**Issue by jmhatch** [trafficonese/leaflet.extras2#12]
I'm not sure this is a `leaflet.extras2` issue, but I thought I'd start here. I'm trying to add wind data to a leaflet map. I download the data using the following link,

> https://nomads.ncep.noaa.gov/cgi-bin/filter_gfs_1p00.pl?file=gfs.t06z.pgrb2.1p00.f000&lev_10_m_above_ground=on&var_UGRD=on&var_VGRD=on&subregion=&leftlon=-72.74273&rightlon=-67.92787&toplat=43.64460&bottomlat=40.04384&dir=%2Fgfs.20201229%2F06

Then I convert the grib file to json using the `weacast-grib2json` program,

```
grib2json -d -n -o gfs.t06z.pgrb2.1p00.f000 gfs.t06z.pgrb2.1p00.f000.json
```

Basically following the guidance found [here](https://github.com/cambecc/earth) and [here](https://github.com/cambecc/earth/issues/110).

However, when I display the wind data on my leaflet map,

```
leaflet() %>%
    setView(lng = -70.3361, lat = 41.8451, zoom = 10) %>%
    addProviderTiles(providers$Esri.WorldImagery) %>%
    addVelocity(content = 'gfs.t06z.pgrb2.1p00.f000.json')
```

it looks different than what is displayed on [windy](https://www.windy.com/?gfs,41.810,-70.508,9) or [earth](https://earth.nullschool.net/#current/wind/surface/level/orthographic=-70.89,42.45,5107) (the angle of the particles looks off). Not sure what is going on...

Windy

![windy](https://user-images.githubusercontent.com/35869229/103293688-57c3dd80-49be-11eb-8f6a-553d6914aa53.PNG)

vs. mine

![manual](https://user-images.githubusercontent.com/35869229/103293709-5eeaeb80-49be-11eb-89e3-18c03942a0c9.PNG)

Maybe it's a projection issue?

**Comment by trafficonese** [comment]
Hey @jmhatch, that is very interesting indeed. Unfortunately I have no idea, where this "bug" is coming from. I will have a look at my code but I'm pretty sure I just pass the json to the underlying plugin-library. So no transformation is happening on my side.

Are you sure that you were looking at the same timeranges? I guess a time difference of 1 hour can already make a huge difference.

**Comment by jmhatch** [comment]
I'm pretty sure it's the same time range. Here is another example, with a ref time of 2021-02-09T06:00:00.000Z from the json file I downloaded, which seems to correspond with what Windy is reporting for GFS.

Windy
![windy_2](https://user-images.githubusercontent.com/35869229/107376986-7d153280-6ab8-11eb-842c-a029623201dd.PNG)

vs. mine
![mine_2](https://user-images.githubusercontent.com/35869229/107377013-82727d00-6ab8-11eb-908a-144bb15079be.PNG)

The discrepancy is pretty apparent. I must be doing something wrong?

**Comment by trafficonese** [comment]
Could you maybe try to use the json file with the underlying JS-library?
Unfortunately, I am not able to install `grib2json` on my computer, so its a bit hard for me to debug..

**Comment by jmhatch** [comment]
Good idea @trafficonese!

I was able to replicate the 'mine' image above using the leaflet-velocity JS library. So it isn't a `leaflet.extras2` issue. It must be a  data issue. I'll open up an issue over at leaflet-velocity to see if someone can help me out.

Thanks!

![Capture](https://user-images.githubusercontent.com/35869229/109196440-b52f9d00-7769-11eb-8f1b-896bb17dacd3.PNG)
