### ISSUE TITLE
Implement search for circle markers

### ISSUE THREAD

**Issue by wyuill** [trafficonese/leaflet.extras2#15]
Leaflet.extras has a search feature which currntly only works with markers. A [edit of the  lfx-search-prod.js file](https://github.com/bhaskarvk/leaflet.extras/issues/143#issuecomment-450461384) allows the search feature to also work with circle makers. However, this makes it hard to publish or share code. Would it be possible to enable this change in leaflet.extras2? This can be really useful when there are a large number of points or points over a wide area.

**Comment by trafficonese** [comment]
I understand this would be a great addition, but somehow I would prefer the fix to be merged into `leaflet.extras`.

I hope we can find a maintainer for leaflet.extras soon, as there are a lot of nice plugins there and also a lot of good PR already.

**Comment by radbasa** [comment]
I do wonder what happened to `leaflet.extras`, @trafficonese . It's been 2 years 1 month since it was last updated. There are indeed a lot of useful plugins there.

**Comment by wyuill** [comment]
Now that leaflet.extras has been archived I wondered if opinions on how this feature additional could be implemented have changed, especially given the package it is based on has a number of updates since it was originally added.

**Comment by trafficonese** [comment]
I will take over `leaflet.extras` and hope to be able to bring a new release soon.
I will close the issue here.
