### ISSUE TITLE
Implementation of Labelgun Plugin

### ISSUE THREAD

**Issue by Fsttro** [trafficonese/leaflet.extras2#16]
Hi,
thank you very much for all the work you've put in leaflet extras 2 so far.
I think it would be great to implement the [Labelgun Plugin](https://github.com/Geovation/labelgun)
It avoids the collision of labels, if labels are always shown.
Personally, I would use it for city map designs when a lot of markers are in a relatively small place.
I believe it would be of use to anyone who wishes to always show certain marker attributes, e.g. the names of places.

**Comment by trafficonese** [comment]
Hello,
Although this looks like a nice plugin and I would need this functionality in some of my projects as well, I don't think there is an easy and general way to implement this plugin.
Hopefully someone can prove me wrong.

Maybe [Leaflet.LabelTextCollision](https://github.com/yakitoritabetai/Leaflet.LabelTextCollision) could be an alternative, although it requires to change the `renderer` of the map itself?

**Comment by radbasa** [comment]
I wonder if Labelgun works with leaflet R's `addmarkers(label ="...", labelOptions = labelOptions(...))`

**Comment by radbasa** [comment]
Labelgun Plugin might be doable.

Looking at the Leaflet example https://geovation.github.io/labelgun/examples/leaflet/index.html

The labels are in the `leaflet-tooltip-pane` `div`:
```
<div id="map" class="leaflet-container ..." ...>
  <div class="leaflet-pane..." ...>
    ...
    <div class="leaflet-pane leaflet-tooltip-pane">
      <div class="leaflet-tooltip leaflet-zoom-animated leaflet-tooltip-left"...>
        ::before
        "Test 0"
      </div>
      ...
    </div>
</div>
```

In the Leaflet for R docs for Popups and Labels, Customizing Marker Labels https://rstudio.github.io/leaflet/popups.html#customizing-marker-labels

If we use `noHide = T` as demonstrated 
```
leaflet() %>%
  addMarkers(
    lng = ..., lat = ...,
    label = "Default Label",
    labelOptions = labelOptions(noHide = T)) %>%
    ...
```

The labels also show up in the `leaflet-tooltip-pane`
```
<div id="htmlwidget..." class="leaflet..." ...>
  <div class="leaflet-pane..." ...>
    ...
    <div class="leaflet-pane leaflet-tooltip-pane">
      <div class="leaflet-tooltip leaflet-zoom-animated leaflet-tooltip-left" ...>
        ::before
        "Default Label"
      </div>
    </div>
</div>
```

This might make the LabelGun plugin doable.

**Comment by radbasa** [comment]
However, both LabelGun and Leaflet.LabeTextCollision seem to have been abandoned. Their last commits are 2017 and 2019.

@trafficonese what's the protocol on using seemingly inactive plugins? I'm also looking at [Leaflet.GroupedLayerControl](https://github.com/ismyrnow/leaflet-groupedlayercontrol) last commit 2018.

**Comment by trafficonese** [comment]
Indeed, Labelgun is doable. You can test out the PR and see the example app in `inst/examples/labelgun_app.R`
