### ISSUE TITLE
Implement LabelTextCollision Plugin

### ISSUE THREAD

**Issue by rlh1994** [trafficonese/leaflet.extras2#20]
Hi,

I've recently come across the LabelTextCollision plugin as a solution to being able to always label your points but not have them all overlap so that they are entirely unreadable. Unfortunately I don't know enough JS/R to be able to contribute directly to the repo but was hoping it might be possible to implement this at some point.

Source:
https://github.com/yakitoritabetai/Leaflet.LabelTextCollision

**Comment by trafficonese** [comment]
I decided in favor of labelgun instead.

The problem with Leaflet.LabelTextCollision is that the map needs a different `renderer` and I didn't manage to make that work.

But since both plugins share the same goal, I think it's ok if I close this issue.
