### ISSUE TITLE
Disable WMS getFeatureInfo popup

### ISSUE THREAD

**Issue by MarcusChMa** [trafficonese/leaflet.extras2#22]
I am trying to disable the `getFeatureInfo` pop-up in `addWMS` from the WMS plugin. In the original plugin page, there is a mention of a `options.identify` option that can be set to `FALSE`, however I have not found out how to do this in the `leaflet.extras2` plugin. Is it possible to disable it in R? Thank you for your help!

**Comment by trafficonese** [comment]
Indeed, that's currently not possible and I also wanted to have that feature. I will implement it as soon as possible.

**Comment by MarcusChMa** [comment]
Thank you for your reply, looking forward!

**Comment by trafficonese** [comment]
I was wrong, you can just pass the option `identify`. It is passed along and should work with the current version.
Here's an example:

```
library(leaflet)
library(leaflet.extras2)

leaflet() %>%
  addTiles(group = "base") %>%
  setView(9, 50, 5) %>%
  addWMS(baseUrl = "https://maps.dwd.de/geoserver/dwd/wms",
         layers = "dwd:BRD_1km_winddaten_10m",
         popupOptions = popupOptions(maxWidth = 600),
         options = WMSTileOptions(
           identify = FALSE,
           transparent = TRUE,
           format = "image/png",
           info_format = "text/html"))
```
