### ISSUE TITLE
Pulse Icon

### ISSUE THREAD

**Issue by jlbarr** [trafficonese/leaflet.extras2#23]
The original leaflet.extras has been abandoned and it advises not to use it.  Could you implement the pulseIcon that is in that package into yours?

**Comment by trafficonese** [comment]
Is the pulseIcon function from leaflet.extras not working as expected or are there bugs to be fixed?

I still use `leafet.extras` heavily and wouldn't give it up right away. I also don't necessarily want to copy code from another package if the function is running fine anyway. I hope that makes sense.

**Comment by trafficonese** [comment]
I am now also maintaining `leaflet.extras` and I plan on releasing a new CRAN version soon, but the current Github version is updated including most of the JS-dependencies. So I'll close this issue here.
