### ISSUE TITLE
Plugin Request: WebGL Earth Map 2

### ISSUE THREAD

**Issue by jzadra** [trafficonese/leaflet.extras2#25]
As far as I can tell there is currently no way to show a globe with R leaflet.  There is, however, a project that will take a leaflet map and make it into a globe:  https://www.maptiler.com/news/2014/07/webgl-earth-2-leaflet-compatible/

It would be great to have a way to do this with R!

**Comment by trafficonese** [comment]
It seems that the project is not maintained anymore and they are recommending to use Cesium. 
There is an R-package for that already: https://github.com/r-spatial/cesium

Would that also work for you?

Otherwise I can still look into it.

**Comment by jzadra** [comment]
I'll take a look at it and get back to you.  It does not appear to have been updated since 2 years ago, and has no help documentation.

**Comment by trafficonese** [comment]
You are right, it does not seem to be fully working yet. You can render a globe, but not add any features on it.
There is an example here [usecase1](https://github.com/r-spatial/cesium/blob/master/usecases/usecase1.R)

**Comment by trafficonese** [comment]
This library is not really a leaflet-plugin, it is more a replacement of leaflet. 
Based on the documentation all you have to do on the JS-side is to replace `L` with `WE`.
This can't be done here.
