### ISSUE TITLE
add options to playbackOptions()

### ISSUE THREAD

**Issue by gacolitti** [trafficonese/leaflet.extras2#27]
Would be nice to have the `orientIcons`, `labels`, and `popups` options described here:

https://github.com/hallahan/LeafletPlayback

**Comment by trafficonese** [comment]
The arguments can be set via `...`, but for `orientIcons` to take effect, you have to assign `iconAnchorX` and `iconAnchorY` to the icon. 

I will however add `orientIcons` to the `playbackOptions` as separate argument in the next commit.

The arguments `popups` and `labels` can also be set via `...` but are either true/false and don't really have any effect currently. I am just working on a fix to the original js-library, which allows to set popups and labels for each point in the timeseries.

**Comment by gacolitti** [comment]
That's great! 

Because I want labels/popups that are dynamic, I am implementing an approach currently that removes and then replaces moving markers based on the time sourced from a `sliderInput()` inside a shiny app. Then uses `moveToMoving()` to accomplish smooth transitions.

But if you implement dynamic popups/labels here, I might be able to abandon this hacky approach.

**Comment by trafficonese** [comment]
Hey, I just pushed [99b6e7c](https://github.com/trafficonese/leaflet.extras2/commit/99b6e7ceb0b825f69fe2ce6c9bfb7f28f936b665) with upgrades to the playback plugin. It is now possible to use a formula for the popup and label arguments. I hope everything works as expected, I know it's not very clear from the docs, what all these options of the plugin really do :D. 

I found it quite confusing and probably buggy when the time steps are bigger (several hours) and the options (tickLen, speed, etc..) are not set "correctly"..

Feel free to reopen the issue, if you find some problems.
