### ISSUE TITLE
movingMarkerOptions(autostart = FALSE) ignored

### ISSUE THREAD

**Issue by gacolitti** [trafficonese/leaflet.extras2#28]
The following example has argument `autostart = FALSE` and yet the markers start automatically:

https://github.com/trafficonese/leaflet.extras2/blob/master/inst/examples/movingmarker_app.R

**Comment by trafficonese** [comment]
Hey, you're right, the argument doesn't seem to have an effect. But the example has `autostart = TRUE`.

I will look into it.

**Comment by trafficonese** [comment]
I just pushed [e14bc6f](https://github.com/trafficonese/leaflet.extras2/commit/e14bc6fb01ad9f469216639445a984c92b8e84d9) which fixes this problem.
