### ISSUE TITLE
addWMS() is not showing the maps

### ISSUE THREAD

**Issue by MoritzMennenga** [trafficonese/leaflet.extras2#3]
I'd I tried around a lot, but addWMS() doenst't work in my case. I tried it with my data first and then I used your example https://github.com/trafficonese/leaflet.extras2/blob/master/inst/examples/wms_popup.R. If I use leaflet.extras2::addWMS() there is no WMS displayed. If I use the same with addWMSTiles (and without the popup) I can see the WMSmap but I can't use the popup Feature for the getFeatureInformation I really need.

`- Session info --------------------------------------------------------------------------
 setting  value                       
 version  R version 3.5.1 (2018-07-02)
 os       Windows >= 8 x64            
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  German_Germany.1252         
 ctype    German_Germany.1252         
 tz       Europe/Berlin               
 date     2020-06-15                  

- Packages ------------------------------------------------------------------------------
 package         * version    date       lib source                                       
 assertthat        0.2.1      2019-03-21 [1] CRAN (R 3.5.3)                               
 cli               1.1.0      2019-03-19 [1] CRAN (R 3.5.3)                               
 crayon            1.3.4      2017-09-16 [1] CRAN (R 3.5.1)                               
 crosstalk         1.1.0.1    2020-03-13 [1] CRAN (R 3.5.3)                               
 digest            0.6.18     2018-10-10 [1] CRAN (R 3.5.3)                               
 fastmap           1.0.1      2019-10-08 [1] CRAN (R 3.5.3)                               
 htmltools         0.4.0      2019-10-04 [1] CRAN (R 3.5.3)                               
 htmlwidgets       1.5.1      2019-10-08 [1] CRAN (R 3.5.3)                               
 httpuv            1.5.2      2019-09-11 [1] CRAN (R 3.5.3)                               
 jsonlite          1.6        2018-12-07 [1] CRAN (R 3.5.3)                               
 later             1.0.0      2019-10-04 [1] CRAN (R 3.5.3)                               
 lattice           0.20-38    2018-11-04 [1] CRAN (R 3.5.1)                               
 leaflet         * 2.0.3      2019-11-16 [1] CRAN (R 3.5.3)                               
 leaflet.extras2 * 1.0.0.9000 2020-06-12 [1] Github (trafficonese/leaflet.extras2@4ed1748)
 magrittr          1.5        2014-11-22 [1] CRAN (R 3.5.3)                               
 mime              0.6        2018-10-05 [1] CRAN (R 3.5.2)                               
 promises          1.1.0      2019-10-04 [1] CRAN (R 3.5.3)                               
 R6                2.4.0      2019-02-14 [1] CRAN (R 3.5.3)                               
 Rcpp              1.0.1      2019-03-17 [1] CRAN (R 3.5.3)                               
 rlang             0.4.5      2020-03-01 [1] CRAN (R 3.5.3)                               
 rsconnect         0.8.16     2019-12-13 [1] CRAN (R 3.5.3)                               
 rstudioapi        0.11       2020-02-07 [1] CRAN (R 3.5.3)                               
 sessioninfo     * 1.1.1      2018-11-05 [1] CRAN (R 3.5.3)                               
 shiny           * 1.4.0.2    2020-03-13 [1] CRAN (R 3.5.3)                               
 sp              * 1.3-1      2018-06-05 [1] CRAN (R 3.5.3)                               
 withr             2.1.2      2018-03-15 [1] CRAN (R 3.5.3)                               
 XML             * 3.99-0.3   2020-01-20 [1] CRAN (R 3.5.3)                               
 xtable            1.8-4      2019-04-21 [1] CRAN (R 3.5.3)                               
 yaml              2.2.0      2018-07-25 [1] CRAN (R 3.5.2)    `

**Comment by trafficonese** [comment]
Do you see any errors in the browser console?
Could you install the Github version without error/warnings? And do you also see the same behavour with the CRAN version?

**Comment by MoritzMennenga** [comment]
Solved. I tried it all the time in the R-Studio Preview and didn't start it in the browser...
It worked there. Thanks a lot for this package!

**Comment by trafficonese** [comment]
Hm, still interesting as it works in my R-Studio preview aswell. But I am glad it is solved for you!
