### ISSUE TITLE
"CurrentSize" for sizeModes in easyprintMap not working

### ISSUE THREAD

**Issue by super-lou** [trafficonese/leaflet.extras2#30]
Hi, thank's a lot for your work (that deserve more visibility given the time i spent to find it) !

However, i get an empty png when I use the "CurrentSize" option in an external Shiny button with easyprintMap.
The  "CurrentSize" option is mention in help of [easyprint.R](https://github.com/trafficonese/leaflet.extras2/blob/master/R/easyprint.R) but it seems that there is also the "Current" option. Moreover, it is the "Current" option that work in the easyprintOptions of addEasyprint.

line 95
>#' @param sizeModes Options available include \code{CurrentSize}, \code{A4Portrait},
>#'   \code{A4Landscape} or a custom size object

line 119 
> sizeModes = list("A4Portrait", "A4Landscape", "Current"),

So i tried to use the "Current" option in easyprintMap but when i hits the button print the app freeze ... Not shure if it is just me or a real bug and not shure how to fix it so i lets this example below which is a sligthly modify version of your help example.

```
library(shiny)
library(leaflet)
library(leaflet.extras2)

ui <- fluidPage(
    leafletOutput("map"),
    selectInput("scene", "Select Scene", choices=c("Current",
                                                   "A4Landscape",
                                                   "A4Portrait")),
    actionButton("print", "Print Map")
)

server <- function(input, output, session) {
    output$map <- renderLeaflet({
        input$print
        leaflet()  %>%
            addTiles() %>%
            setView(10, 50, 9) %>%
            addEasyprint(options=easyprintOptions(
                             sizeModes=c("Current",
                                         "A4Landscape",
                                         "A4Portrait"),
                             exportOnly=TRUE
                         ))
    })
    observeEvent(input$print, {
        leafletProxy("map") %>%
            easyprintMap(sizeModes=input$scene)
    })
}

shinyApp(ui, server)
```

Thank's by advance

**Comment by trafficonese** [comment]
I will look into it, I remember I had to include a workaround to make the normal options work and unfortunately the plugin itself does not really seem to be actively maintained anymore.

**Comment by trafficonese** [comment]
The CurrentSize will work with the control-buttons inside the map, but not with the function `easyprintMap` and I really dont understand why. If someone has enough nerves and time to dive into it, I would be very grateful to him.

**Comment by super-lou** [comment]
I don't know what to say except that it works like that lol... As visible below I have changed the `Current` to `CurrentSize` and I have deleted the line `input$print` in the `renderLeaflet`.

``` r
library(shiny)
library(leaflet)
library(leaflet.extras2)

ui <- fluidPage(
    leafletOutput("map"),
    selectInput("scene", "Select Scene", choices=c("CurrentSize", #"Current",
                                                   "A4Landscape",
                                                   "A4Portrait")),
    actionButton("print", "Print Map")
)

server <- function(input, output, session) {
    output$map <- renderLeaflet({
        # input$print
        leaflet()  %>%
            addTiles() %>%
            setView(10, 50, 9) %>%
            addEasyprint(options=easyprintOptions(
                             sizeModes=c("CurrentSize", #"Current",
                                         "A4Landscape",
                                         "A4Portrait"),
                             exportOnly=TRUE
                         ))
    })
    observeEvent(input$print, {
        leafletProxy("map") %>%
            easyprintMap(sizeModes=input$scene)
    })
}

shinyApp(ui, server)
```

**Comment by trafficonese** [comment]
Indeed it does. Very interesting! Thanks for looking into it!
