### ISSUE TITLE
Possibility with easyPrint to print also a Shiny panel on map

### ISSUE THREAD

**Issue by super-lou** [trafficonese/leaflet.extras2#34]
Hi, the easyPrint user again! Is there a way to make easyPrint able to also print a Shiny panel (or even an actionButton) with the map as in the example below ? Could it be done with a vector of Shiny id for example ?

``` r
library(shiny)
library(leaflet)
library(leaflet.extras2)

ui <- fluidPage(
    leafletOutput("map"),
    selectInput("scene", "Select Scene", choices=c("CurrentSize",
                                                     "A4Landscape",
                                                     "A4Portrait")),
    actionButton("print", "Print Map"),

    absolutePanel(
        id="panel",
        style="background-color: rgba(200, 200, 200, 0.9);",
        fixed=TRUE,
        width="auto", height="auto",
        right=50, top=50,
        tags$h1("Title")
        )
        
)

server <- function(input, output, session) {
    output$map <- renderLeaflet({
        input$print
        leaflet()  %>%
            addTiles() %>%
            setView(10, 50, 9) %>%
            addEasyprint(options=easyprintOptions(exportOnly=TRUE))
    })
    observeEvent(input$print, {
        leafletProxy("map") %>%
            easyprintMap(sizeModes=input$scene)
    })
}

shinyApp(ui, server)
```

**Comment by trafficonese** [comment]
The problem is that the panel will not be inside the map div.
There is not really a "normal" way to do this, but you can use `shinyjs` and insert the panel inside the map-div and change the position to absolute. That will put it on the image.

```
library(shiny)
library(leaflet)
library(leaflet.extras2)
library(shinyjs)

ui <- fluidPage(
  useShinyjs(),
  leafletOutput("map"),
  selectInput("scene", "Select Scene", choices=c("CurrentSize",
                                                 "A4Landscape",
                                                 "A4Portrait")),
  actionButton("print", "Print Map"),
  
  absolutePanel(
    id="panel",
    style="background-color: rgba(200, 200, 200, 0.9);",
    fixed=TRUE,
    width="auto", height="auto",
    right=50, top=50,
    tags$h1("Title")
  )
)

server <- function(input, output, session) {
  output$map <- renderLeaflet({
    input$print
    leaflet()  %>%
      addTiles() %>%
      setView(10, 50, 9) %>%
      addEasyprint(options=easyprintOptions(exportOnly=TRUE,
                                            hideControlContainer=FALSE))
  })
  observe({
    runjs('
          $("#panel").insertAfter($(".leaflet-pane.leaflet-map-pane"));
          $("#panel").css("position", "absolute");
          ')
  })
  observeEvent(input$print, {
    leafletProxy("map") %>%
      easyprintMap(sizeModes=input$scene)
  })
}

shinyApp(ui, server)

```

**Comment by super-lou** [comment]
Thank you ! I understand the idea but the example given doesn't work for me... don't know if it should. I still can't see on the print the panel. No update on the repo ?

**Comment by trafficonese** [comment]
No, no updates on the repo. Nothing to do there really..
I updated the example, maybe the `runjs` was running, before the panel was created, so i delayed it by 500ms.

**Comment by super-lou** [comment]
Wooo javascript is still sorcery to me but it finally works. Thanks again !

**Comment by super-lou** [comment]
The solution you gave me definitely works with the example above, but when I tried to implement it in my code, I had problems... Actually, I have two maps of leaflets on top of each other for obscure reasons... But in this configuration, the printing of a panel that can be hidden does not work. And obviously, if I remove my `mapPreview_div` everything works fine.
Also, in this configuration, the `"CurentSize"` mode takes a screenshot but not of the right size. I think it's due to the use of % in `leafletOutput` because it doesn't work with `height="100%"` but with `height="400"` everything works fine.

There are so many gaps in my knowledge of javascript and I've spent so much time trying to get it to work. If you still have some time for me, I'll be happy!

``` r
library(shiny)
library(leaflet)
library(leaflet.extras2)
library(shinyjs)

ui = bootstrapPage(

    useShinyjs(),

    tags$head(tags$style(
             ".leaflet-control-easyPrint.leaflet-bar.leaflet-control
             {display: none;}")),

    tags$body(
             tags$div(id='mapPreview_div',
                      style="position: absolute;
                    top: 0; bottom: 0; left: 0; right: 0;",
                    leafletOutput("mapPreview", width="100%",
                                  height="100%")),
             
             tags$div(id='map_div',
                      style="position: absolute;
                    top: 0; bottom: 0; left: 0; right: 0;",
                    leafletOutput("map", width="100%",
                                  height="100%")),
             ),
    
    absolutePanel(
        id="control_panel",
        style="background-color: rgba(200, 200, 200, 0.9);",
        fixed=TRUE,
        width="auto", height="auto",
        left=50, bottom=50,
        
        selectInput("scene", "Select Scene", choices=c("CurrentSize",
                                                       "A4Landscape",
                                                       "A4Portrait")),
        actionButton("print", "Print Map"),
        
        actionButton("show", "Show Title")),
    
    hidden(
        absolutePanel(
            id="title_panel",
            style="background-color: rgba(200, 200, 200, 0.9);",
            fixed=TRUE,
            width="auto", height="auto",
            right=50, top=50,
            tags$h1("Title")
        )
    )
)


server = function(input, output, session) {
    
    output$map <- renderLeaflet({
        leaflet()  %>%
            addTiles() %>%
            setView(10, 50, 9) %>%
            addEasyprint(options=easyprintOptions(exportOnly=TRUE,
                                                  hideControlContainer=TRUE,
                                                  hidden=TRUE))
    })
    
    output$mapPreview <- renderLeaflet({
        leaflet()
    })

    observeEvent(input$show, {
        toggle(id="title_panel")
    })
    
    observe({
        delay(500,
              runjs('
      $("#title_panel").insertAfter($(".leaflet-pane.leaflet-map-pane"));
      $("#title_panel").css("position", "absolute");
      $("#title_panel").css("z-index", "999");
           ')
      )
    })
    
    observeEvent(input$print, {
        leafletProxy("map") %>%
            easyprintMap(sizeModes=input$scene)
    })
}

shinyApp(ui, server)
```

**Comment by trafficonese** [comment]
So, you only want the title to show, when a user clicked on "Show Title" or always?
I also dont really understand why you have 2 maps as one is just empty, but you are inserting the absolute panel in the first map.

You have to be more specific with the css selector. Try this line:
`$("#title_panel").insertAfter($("#map_div .leaflet-pane.leaflet-map-pane"));`

I will look into the problem with height=100%. I know there are several issues about it on the original repo.

**Comment by super-lou** [comment]
I wanted it to work as you said. I have several panels in my app that are optional to show, but when they are, they should be in the screenshot. And ok thank you very much I learned something again. I have tried something like this but I was changing the `map` from `leaflet-map-pane`...

If you want the explanation I have a map for user normal purposes and a second to "preview" the action like `fitBounds` with the padding option... Actually I want to check if the map accessible to the user already fit to a bunch of markers on the map or not. So the preview map always fits markers and I check if the visble limits of the user map is similar or not and let the possibility to the user to click a button that will adjust the user map around markers (like the preview map). Not sure if I'm clear but the problem is that I can't managed to access the fitBounds coordinates with padding (because it depends on the zoom of the leaflet) until I've actually done it, hence my two maps... I know, I am really not proud of these lines...

**Comment by super-lou** [comment]
> but you are inserting the absolute panel in the first map.
I am not shure to understand you but I don't know how you can tell that my `title_panel` is more in the `map` or in the `mapPreview` ... Is this linked with the order of appearance in the server function ?

**Comment by trafficonese** [comment]
You can browse inside the Html to see where it is.

The original line:
`$("#title_panel").insertAfter($(".leaflet-pane.leaflet-map-pane"));`
was inserting the `#title_panel` into the HTML with a CSS Selector (`$('.leaflet-pane.leaflet-map-pane')`) , and because there were 2 maps on the page, JS was inserting the title_panel into the first option. 

So now we change the CSS-selector to `$("#map_div .leaflet-pane.leaflet-map-pane")`. Then the panel is included at the correct position inside the HTML tree.

**Comment by super-lou** [comment]
To be sure, you browsed inside the Html from your web browser but shiny can't show it to you from the R console? 
Ok I understand, completely logical ! But there is no "shiny-iest" way to control such issues otherwise than using runjs as you do?
