### ISSUE TITLE
Contribute guide

### ISSUE THREAD

**Issue by HuangLiPang** [trafficonese/leaflet.extras2#36]
Hi @trafficonese 

Could you provide a simple guide to indicate how to contribute to this repo? I want to add some library to leaflet.extras2, but I don't know how to start it. I read through the antpath binding js but don't know what is `LeafletWidget`.

Thank you!

**Comment by trafficonese** [comment]
Hey, yeah that's a good idea. I will try to come up with a little How-To readme. I think I will use the FR #37 for it, as it's quite straightforward and I implemented that plugin already somewhere.

**Comment by trafficonese** [comment]
@HuangLiPang I just published a HowTo tutorial. Feel free to check it out and tell me if you miss something.

**Comment by HuangLiPang** [comment]
@trafficonese Thank you!
