### ISSUE TITLE
awesomeIcons in addMovingMarker for direction

### ISSUE THREAD

**Issue by vanhry** [trafficonese/leaflet.extras2#38]
Hello!
I'm using great function from your project `addMovingMarker`. It works fine. But I'm trying to use `makeAwesomeIcon` instead of `makeIcon`, because it's important for me to rotate icon during visualization.
Is it possible to do it with `makeAwesomeIcon` or with some other function?
Thank you for any help you can offer!
There is a code:

```
library(shiny)
library(sf)
library(leaflet)
library(leaflet.extras2)
df <- sf::st_as_sf(atlStorms2005)[1,]
dfp <- suppressWarnings(st_cast(df, "POINT"))
dfp$duratios = sample(c(1000, 1500, 2000, 2500, 3000), nrow(dfp), TRUE)

# it works
shipIcon <- makeIcon(
  iconUrl = "https://cdn-icons-png.flaticon.com/512/1355/1355883.png",
  iconWidth = 40, iconHeight = 50,
  iconAnchorX = 0, iconAnchorY = 0
)

# it doesn't work
shipIcon2 <- makeAwesomeIcon(icon = "arrow-up",
                iconRotate = 90,
                squareMarker = TRUE,
                markerColor = "black")

ui <- fluidPage(
              leafletOutput("map", height = 800)))

server <- function(input, output, session) {
  output$map <- renderLeaflet({
    leaflet()  %>% addTiles() %>%
      addPolylines(data = df) %>%
      addMovingMarker(data = dfp,
                      duration = ~duratios,
                      icon = shipIcon2,
                      movingOptions = movingMarkerOptions(autostart = TRUE,
                                                          loop = TRUE,
                                                          pauseOnZoom = TRUE)
      )
  })
}
shinyApp(ui, server)
```

**Comment by trafficonese** [comment]
@vanhry Hey, I just pushed [f74d994](https://github.com/trafficonese/leaflet.extras2/commit/f74d994c042c6259ab5a03ff0020edf5a833f8fc) which makes it possible to use `awesomeIcons`.

**Comment by vanhry** [comment]
@trafficonese thank you for such a quick response! Is it possible that the marker left behind the path that he passed?

**Comment by trafficonese** [comment]
I'm not sure I understand the question..
Do you want the icon to stay at the locations he passed? That would not be possible I think.

**Comment by vanhry** [comment]
@trafficonese polyline after the movingmarker, which would mark path that marker already passed

**Comment by trafficonese** [comment]
no unfortunately, that is not possible.

**Comment by vanhry** [comment]
@trafficonese I understand, thank you. I have another question, is it possible to put multiple moving markers on the map? (but without repeating `%>% addMovingMarker` again and again)

**Comment by trafficonese** [comment]
No that is also not possible.
