### ISSUE TITLE
addEasyprint does only export the top part of a map for "Current Size"

### ISSUE THREAD

**Issue by myxBeni** [trafficonese/leaflet.extras2#44]
First of all, many thanks for the great work!

The (wonderful !) easyprint-button only exports the first row of tiles when setting the extent to current size. A4 seems to work.n Tested on Chrome and Safari with the latest version of leaflet.extras2.

```r
pacman::p_load(dplyr, leaflet, leaflet.extras2)

m <- gadmCHE %>% leaflet() %>%
  addPolygons(fillColor = ~colors(NAME_1), fillOpacity = 1,group = "Kantone") %>%
  leaflet.extras2::addEasyprint(options = easyprintOptions(position = "topright",
                                            exportOnly=FALSE, #or true does not change much
                                            filename ="Anmerkung")
              )

htmlwidgets::saveWidget(m,"test_export.html")
```
![Anmerkung-6](https://user-images.githubusercontent.com/109787519/185618432-df5fd0c1-9043-4384-b9c4-8bf42b679c3a.png)

**Comment by trafficonese** [comment]
If you the same code within a Shiny-app everything seems to work fine..
```
library(shiny)  
library(leaflet)
library(leaflet.extras2)

ui <- fluidPage(leafletOutput("map"))

server <- function(input, output, session) {
  output$map <- renderLeaflet({
    leaflet()  %>%
      addTiles(group = "basemap") %>%
      addPolygons(data = gadmCHE,fillOpacity = 1,group = "Kantone") %>%
      leaflet.extras2::addEasyprint(options = easyprintOptions(position = "topright",
                                                               exportOnly=FALSE, #or true does not change much
                                                               filename ="Anmerkung")
      )
    })
}
shinyApp(ui, server)

```

So not sure entirely sure where the problem might be.. or if i can fix it.

**Comment by myxBeni** [comment]
Indeed, I don't encounter the problem in a Shiny-App opened in a Browser (Firefox and Safari). However, I need to distribute the app to several machines and currently. As we don't run a shiny server, I distributed the HTML...
