### ISSUE TITLE
addSidebar causing issues if multiple leaflet maps are in one R shiny app

### ISSUE THREAD

**Issue by adamhaywood307** [trafficonese/leaflet.extras2#57]
In an R shiny app containing a single leaflet map (id ="map") with sidebars, everything works as intended. When another leaflet map (id = "map2") is included anywhere in the app, the sidebars in "map" fail to load and properly render. Additionally, one or both of "map" sidebars appear in "map2".

A reproducible example is shown below. I expected "map" to have two fully functioning sidebars and "map2" to have no sidebars. Instead, "map" has two non-functioning sidebars and "map2" has one of "map"'s non-functioning sidebars. Any help is much appreciated.

`library(sf)
library(shiny)
library(leaflet)
library(leaflet.extras2)

data(breweries91, package = "leaflet")

ui <- fluidPage(
  h4("Leaflet Sidebar Plugin"),
  splitLayout(
    cellWidths = c("27%", "73%"),
    tagList(
      actionButton("open", "Open Sidebar"),
      actionButton("close", "Close Sidebar"),
      actionButton("clear", "Clear Sidebar")
   ),
    tagList(
      leafletOutput("map", height = "700px", width = "100%"),
      ## Sidebar 1 #############
      sidebar_tabs(id = "mysidebarid",
        list(icon("car"), icon("user"), icon("envelope")),
        ## Sidebar 1 - Pane #############
        sidebar_pane(
          title = "home", id = "home_id", icon = icon("home"),
          tagList(
            sliderInput("obs", "Number of observations:",
                        min = 1, max = 32, value = 10),
            sliderInput("opa", "Point Opacity:",
                        min = 0, max = 1, value = 0.5),
            sliderInput("fillopa", "Fill Opacity:",
                        min = 0, max = 1, value = 0.2),
            dateRangeInput("daterange4", "Date range:",
                           start = Sys.Date() - 10,
                           end = Sys.Date() + 10),
            verbatimTextOutput("tab1")
          )
        ),
        ## Sidebar 1 - Pane #############
        sidebar_pane(
          title = "profile", id = "profile_id", icon = icon("wrench"),
          tagList(
            textInput("caption", "Caption", "Data Summary"),
            selectInput("label", "Label",
                        choices = c("brewery","address", "zipcode", "village")),
            passwordInput("password", "Password:"),
            actionButton("go", "Go"),
            verbatimTextOutput("value")
          )
        ),
        ## Sidebar 1 - Pane #############
        sidebar_pane(
          title = "messages", id = "messages_id", icon = icon("person"),
          tagList(
            checkboxGroupInput("variable", "Variables to show:",
              c("Cylinders" = "cyl",
                "Transmission" = "am",
                "Gears" = "gear")),
            tableOutput("data")
          )
        )
      ),
      ## Sidebar 2 #############
      sidebar_tabs(id = "animalsidebar",
                   list(icon("kiwi-bird"), icon("frog")),
                   ## Sidebar 2 - Pane #############
                   sidebar_pane(
                     title = "kwi", id = "kiwi_id", icon = icon("kiwi-bird"),
                     tagList(
                       p("Kiwi birds are awesome.")
                     )
                   ),
                   ## Sidebar 2 - Pane #############
                   sidebar_pane(
                     title = "frog", id = "frog_id", icon = icon("frog"),
                     tagList(
                       p("No frogs are better.")
                     )
                   )
      )
    )
   ),
   leafletOutput("map2", height = "700px", width = "100%"),
)

## Server ############
server <- function(input, output, session) {
  output$map <- renderLeaflet({
    leaflet() %>%
      addTiles() %>%
      ## Add Controls on all sides #########
      addEasyButton(easyButton(position = "topleft",
        icon = htmltools::span(class = "star", htmltools::HTML("&starf;")),
        onClick = JS("function(btn, map){ map.setZoom(1);}"))) %>%
      addEasyButton(easyButton(position = "topright",
        icon = htmltools::span(class = "star", htmltools::HTML("&starf;")),
        onClick = JS("function(btn, map){ map.setZoom(2);}"))) %>%
      addEasyButton(easyButton(position = "bottomright",
        icon = htmltools::span(class = "star", htmltools::HTML("&starf;")),
        onClick = JS("function(btn, map){ map.setZoom(3);}"))) %>%
      addEasyButton(easyButton(position = "bottomleft",
        icon = htmltools::span(class = "star", htmltools::HTML("&starf;")),
        onClick = JS("function(btn, map){ map.setZoom(4);}"))) %>%
      ## Add Sidebar ##########
      addSidebar(
        id = "mysidebarid",
        options = list(position = "left")
      ) %>%
      addSidebar(
        id = "animalsidebar",
        options = list(position = "right")
      )
  })
  observe({
    req(input$obs)
    df <- breweries91[sample.int(nrow(breweries91), input$obs), ]
    bbox <- st_bbox(df)
    leafletProxy("map", session) %>%
      clearGroup("pts") %>%
      addCircleMarkers(data = df,
                       label = df[[input$label]],
                       opacity = input$opa,
                       fillOpacity = input$fillopa,
                       group = "pts") %>%
      fitBounds(bbox[[1]], bbox[[2]], bbox[[3]], bbox[[4]])
  })

  output$tab1 <- renderText({
    input$obs
  })
  output$value <- renderText({
    req(input$go)
    isolate(input$password)
  })
  output$data <- renderTable(rownames = FALSE, {
      mtcars[, c("mpg", input$variable), drop = FALSE]
  })

  observeEvent(input$open, {
    tab_ids <- c(rep("mysidebarid", 3), rep("animalsidebar", 2))
    pane_ids <- c("home_id", "profile_id", "messages_id", "kiwi_id", "frog_id")
    idx <- sample.int(length(pane_ids), 1)
    leafletProxy("map", session) %>%
      openSidebar(pane_ids[idx], tab_ids[idx])
  })
  observeEvent(input$close, {
    leafletProxy("map", session) %>%
      closeSidebar(sample(c("mysidebarid", "animalsidebar"), 1))
  })
  observeEvent(input$clear, {
    leafletProxy("map", session) %>%
      removeSidebar(sample(c("mysidebarid", "animalsidebar"), 1))
  })
  
  
  
  
  
  
  output$map2 <- renderLeaflet({
    leaflet() %>%
      addTiles() %>%
      ## Add Controls on all sides #########
    addEasyButton(easyButton(position = "topleft",
                             icon = htmltools::span(class = "star", htmltools::HTML("&starf;")),
                             onClick = JS("function(btn, map){ map.setZoom(1);}"))) %>%
      addEasyButton(easyButton(position = "topright",
                               icon = htmltools::span(class = "star", htmltools::HTML("&starf;")),
                               onClick = JS("function(btn, map){ map.setZoom(2);}"))) %>%
      addEasyButton(easyButton(position = "bottomright",
                               icon = htmltools::span(class = "star", htmltools::HTML("&starf;")),
                               onClick = JS("function(btn, map){ map.setZoom(3);}"))) %>%
      addEasyButton(easyButton(position = "bottomleft",
                               icon = htmltools::span(class = "star", htmltools::HTML("&starf;")),
                               onClick = JS("function(btn, map){ map.setZoom(4);}")))
  })
  
}
shinyApp(ui, server)
`

**Comment by trafficonese** [comment]
Everything works fine for me. Are you using the current version?
Multiple sidebar only work since `leaflet.extras2` 1.2.0

**Comment by adamhaywood307** [comment]
Thank you for getting back to us so quickly! We confirmed that we are indeed using leaflet.extras2 v 1.2.0. I've attached a screenshot of what the app looks like on our end, perhaps it is a versioning issue with another shiny or leaflet dependency. Any further help is much appreciated.


![multi_sidebar_issues_screenshot](https://user-images.githubusercontent.com/52833562/235733036-57c0dddd-03ec-44ac-9fc0-b17e70bc5281.png)

**Comment by trafficonese** [comment]
Can you post your `sessioninfo::session_info()` and check in the Browser console for any errors?

**Comment by adamhaywood307** [comment]
No errors in the browser console, and the session info is below:

> sessioninfo::session_info()
- Session info --------------------------------------------------------------------------
 setting  value
 version  R version 3.6.3 (2020-02-29)
 os       Windows 10 x64 (build 19045)
 system   i386, mingw32
 ui       RStudio
 language (EN)
 collate  English_United States.1252
 ctype    English_United States.1252
 tz       America/New_York
 date     2023-05-02
 rstudio  2021.09.0+351 Ghost Orchid (desktop)
 pandoc   NA

- Packages ------------------------------------------------------------------------------
 package         * version date (UTC) lib source
 assertthat        0.2.1   2019-03-21 [1] CRAN (R 3.6.3)
 bslib             0.4.0   2022-07-16 [1] CRAN (R 3.6.3)
 cachem            1.0.6   2021-08-19 [1] CRAN (R 3.6.3)
 class             7.3-20  2022-01-13 [1] CRAN (R 3.6.3)
 classInt          0.4-7   2022-06-10 [1] CRAN (R 3.6.3)
 cli               3.3.0   2022-04-25 [1] CRAN (R 3.6.3)
 crayon            1.5.1   2022-03-26 [1] CRAN (R 3.6.3)
 crosstalk         1.2.0   2021-11-04 [1] CRAN (R 3.6.3)
 DBI               1.1.3   2022-06-18 [1] CRAN (R 3.6.3)
 digest            0.6.29  2021-12-01 [1] CRAN (R 3.6.3)
 dplyr             1.0.9   2022-04-28 [1] CRAN (R 3.6.3)
 e1071             1.7-11  2022-06-07 [1] CRAN (R 3.6.3)
 ellipsis          0.3.2   2021-04-29 [1] CRAN (R 3.6.3)
 fansi             1.0.3   2022-03-24 [1] CRAN (R 3.6.3)
 fastmap           1.1.0   2021-01-25 [1] CRAN (R 3.6.3)
 generics          0.1.3   2022-07-05 [1] CRAN (R 3.6.3)
 glue              1.6.2   2022-02-24 [1] CRAN (R 3.6.3)
 htmltools         0.5.2   2021-08-25 [1] CRAN (R 3.6.3)
 htmlwidgets       1.5.4   2021-09-08 [1] CRAN (R 3.6.3)
 httpuv            1.6.5   2022-01-05 [1] CRAN (R 3.6.3)
 jquerylib         0.1.4   2021-04-26 [1] CRAN (R 3.6.3)
 jsonlite          1.8.0   2022-02-22 [1] CRAN (R 3.6.3)
 KernSmooth        2.23-16 2019-10-15 [2] CRAN (R 3.6.3)
 later             1.3.0   2021-08-18 [1] CRAN (R 3.6.3)
 lattice           0.20-45 2021-09-22 [1] CRAN (R 3.6.3)
 leaflet         * 2.1.1   2022-03-23 [1] CRAN (R 3.6.3)
 leaflet.extras2 * 1.2.0   2022-05-10 [1] CRAN (R 3.6.3)
 lifecycle         1.0.1   2021-09-24 [1] CRAN (R 3.6.3)
 magrittr          2.0.1   2020-11-17 [1] CRAN (R 3.6.3)
 memoise           2.0.1   2021-11-26 [1] CRAN (R 3.6.3)
 mime              0.12    2021-09-28 [1] CRAN (R 3.6.3)
 pillar            1.8.1   2022-08-19 [1] CRAN (R 3.6.3)
 pkgconfig         2.0.3   2019-09-22 [1] CRAN (R 3.6.3)
 promises          1.2.0.1 2021-02-11 [1] CRAN (R 3.6.3)
 proxy             0.4-27  2022-06-09 [1] CRAN (R 3.6.3)
 purrr             0.3.4   2020-04-17 [1] CRAN (R 3.6.3)
 R6                2.5.1   2021-08-19 [1] CRAN (R 3.6.3)
 Rcpp              1.0.8.3 2022-03-17 [1] CRAN (R 3.6.3)
 rlang             1.0.3   2022-06-27 [1] CRAN (R 3.6.3)
 rstudioapi        0.13    2020-11-12 [1] CRAN (R 3.6.3)
 sass              0.4.1   2022-03-23 [1] CRAN (R 3.6.3)
 sessioninfo       1.2.2   2021-12-06 [1] CRAN (R 3.6.3)
 sf              * 0.9-8   2021-03-17 [1] CRAN (R 3.6.3)
 shiny           * 1.6.0   2021-01-25 [1] CRAN (R 3.6.3)
 sp              * 1.4-5   2021-01-10 [1] CRAN (R 3.6.3)
 tibble            3.1.7   2022-05-03 [1] CRAN (R 3.6.3)
 tidyselect        1.1.2   2022-02-21 [1] CRAN (R 3.6.3)
 units             0.7-1   2021-03-16 [1] CRAN (R 3.6.3)
 utf8              1.2.1   2021-03-12 [1] CRAN (R 3.6.3)
 vctrs             0.4.1   2022-04-13 [1] CRAN (R 3.6.3)
 withr             2.5.0   2022-03-03 [1] CRAN (R 3.6.3)
 xtable            1.8-4   2019-04-21 [1] CRAN (R 3.6.3)
 yaml              2.3.5   2022-02-21 [1] CRAN (R 3.6.3)

 [1] C:/Users/xxxxxxxx/Documents/R/win-library/3.6
 [2] C:/Program Files/R/R-3.6.3/library

**Comment by adamhaywood307** [comment]
Yes, it's all working perfectly now. We had to also update leaflet the latest version and we're all set. Thank you so much for your help!
