### ISSUE TITLE
Toggle layer on when clicking on a Sidebar-v2 icon

### ISSUE THREAD

**Issue by Daphnisd** [trafficonese/leaflet.extras2#67]
I use the sidebar for descriptions of layers on my map. I was wondering if its possible to detect that an icon is clicked. I was trying something like below but mysidebarid is not part of the input variable.

```r
observeEvent(input$mysidebarid, {
  if ("profile_id"  %in%  input$mysidebarid) {

}
})
```

**Comment by trafficonese** [comment]
This should be fixed in the current development version. Thanks for the input!

**Comment by Daphnisd** [comment]
works great - thanks so much!
