### ISSUE TITLE
Sidebar-v2 - renew map

### ISSUE THREAD

**Issue by Daphnisd** [trafficonese/leaflet.extras2#68]
I have a  leaflet map with a sidebar and want to give the user the option to change the projection.
I thought it would be as simple as just re-rendering the map with the 'Renew Map' button as in the example below. 

The first option I tried 
```r
output$map <- renderLeaflet({
        leaflet() %>
        addTiles() 
  })
```
has the map and icons on the sidebar working well but the open sidebar and close sidebar no longer work.

The second option I tried
```r
output$map <- renderLeaflet({
          leaflet() %>%
          addTiles() %>% 
          removeSidebar() %>% 
          addSidebar(
          id = "mysidebarid",
          options = list(position = "left"))
  })
```
has the open sidebar and close sidebar working but clicking the icons doesn't work. The map also becomes unresponsive sometimes: I can't click and drag to move around the map.

Full minimal example showing the issue below.

```r
library(sf)
library(shiny)
library(leaflet)
library(leaflet.extras2)

data(breweries91, package = "leaflet")

breweries_data <- breweries91 |>
  st_as_sf()

sample_brewery_data <- function(data, n_obs){
  ii <- sample.int(nrow(data),n_obs,replace = TRUE)
  data[ii,]
}

ui <- fluidPage(
  tags$head(tags$style(".btn-default {display: block;}")),
  h4("Leaflet Sidebar Plugin"),
  splitLayout(cellWidths = c("20%", "80%"),
              tagList(
                actionButton("open", "Open Sidebar"),
                actionButton("close", "Close Sidebar"),
                actionButton("clear", "Clear Sidebar"),
                actionButton("renew", "Renew Map"),

                verbatimTextOutput("whichtab")
              ),
              tagList(
                sidebar_tabs(id = "mysidebarid",
                             list(icon("car"), icon("user"), icon("envelope")),
                             sidebar_pane(
                               title = "home", id = "home_id", icon = icon("home"),
                               tagList(
                                 sliderInput("obs", "Number of observations:",
                                             min = 1, max = 32, value = 10),
                                 sliderInput("opa", "Point Opacity:",
                                             min = 0, max = 1, value = 0.5),
                                 sliderInput("fillopa", "Fill Opacity:",
                                             min = 0, max = 1, value = 0.2),
                                 dateRangeInput("daterange4", "Date range:",
                                                start = Sys.Date() - 10,
                                                end = Sys.Date() + 10),
                                 verbatimTextOutput("tab1")
                               )
                             ),
                             sidebar_pane(
                               title = "profile", id = "profile_id", icon = icon("wrench"),
                               tagList(
                                 textInput("caption", "Caption", "Data Summary"),
                                 selectInput("label", "Label",
                                             choices = c("brewery", "address",
                                                         "zipcode", "village")),
                                 passwordInput("password", "Password:"),
                                 actionButton("go", "Go"),
                                 verbatimTextOutput("value")
                               )
                             ),
                             sidebar_pane(
                               title = "messages", id = "messages_id",
                               icon = icon("person", verify_fa = FALSE),
                               tagList(
                                 checkboxGroupInput("variable", "Variables to show:",
                                                    c("Cylinders" = "cyl",
                                                      "Transmission" = "am",
                                                      "Gears" = "gear")),
                                 tableOutput("data")
                               )
                             )
                ),
                leafletOutput("map", height = "700px")
              )
  )
)

server <- function(input, output, session) {
  output$map <- renderLeaflet({
    leaflet() %>%
      addTiles() %>%
      addSidebar(
        id = "mysidebarid",
        options = list(position = "left")
      )
  })
  output$whichtab <- renderPrint({
    paste0(req(input$mysidebarid), " is open")
  })
  
  observe({
    req(input$obs)
    
    df <- breweries_data |>
      sample_brewery_data(n_obs = input$obs)
    
    bbox <- suppressWarnings(st_bbox(df))
    leafletProxy("map", session) %>%
      clearGroup("pts") %>%
      addCircleMarkers(data = df,
                       label = df[[input$label]],
                       opacity = input$opa,
                       fillOpacity = input$fillopa,
                       group = "pts") %>%
      fitBounds(bbox[[1]], bbox[[2]], bbox[[3]], bbox[[4]])
  })
  
  output$tab1 <- renderText({
    input$obs
  })
  output$value <- renderText({
    req(input$go)
    isolate(input$password)
  })
  output$data <- renderTable(rownames = FALSE, {
    mtcars[, c("mpg", input$variable), drop = FALSE]
  })
  
  observeEvent(input$open, {
    leafletProxy("map", session) %>%
      openSidebar(sample(c("home_id","profile_id","messages_id"), 1))
  })
  observeEvent(input$close, {
    leafletProxy("map", session) %>%
      closeSidebar()
  })
  observeEvent(input$clear, {
    leafletProxy("map", session) %>%
      removeSidebar()
  })
  
  observeEvent(input$renew, {
      output$map <- renderLeaflet({
      # leaflet() %>%
      #   addTiles()
        
      leaflet() %>%
          addTiles() %>% 
          removeSidebar() %>% 
          addSidebar(
          id = "mysidebarid",
          options = list(position = "left"))
        

    })
  })
  
 
}
shinyApp(ui, server)
```

**Comment by trafficonese** [comment]
I am not sure what you are trying to achieve and I dont think you should recreate the `output$map` like this. 
Normally you would create 1 map, so use only 1 `renderLeaflet`  and then work with that map via `leafletProxy`. But if you give me some more information maybe I can help you..

**Comment by Daphnisd** [comment]
I've got an map with an Antarctic projection and would like to rotate it. The problem is that leafletProxy doesn't allow changing the crs and I therefore need to regenerate the map. I added the Rotate Map button to show what I'm trying to do.



```r
library(sf)
library(sp)
library(shiny)
library(leaflet)
library(leaflet.extras2)

library(rnaturalearth)
world <- ne_countries(scale = "medium", returnclass = "sf")
antarctica <- world[world$name == "Antarctica", ]

resolutions <- c(238810.813354,119405.406677, 59702.7033384999, 29851.3516692501,14925.675834625,
                 7462.83791731252,3731.41895865639, 1865.70947932806,932.854739664032,
                 466.427369832148, 233.213684916074, 116.60684245803701, 58.30342122888621,
                 29.151710614575396, 14.5758553072877, 7.28792765351156, 3.64396382688807,
                 1.82198191331174, 0.910990956788164, 0.45549547826179, 0.227747739130895,
                 0.113873869697739, 0.05693693484887, 0.028468467424435)
extent<-3.0635955947272874e+07

crsAntartica <- leafletCRS(crsClass = "L.Proj.CRS", 
                           code = "EPSG:3031", 
                           proj4def = "+proj=stere +lat_0=-90 +lat_ts=-71 +lon_0=0 +k=1 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs", 
                           resolutions = resolutions,  
                           origin = c(-3.369955099203E7, 3.369955101703E7), 
                           bounds = list(c(-extent, -extent), c(extent, extent))
)

crsAntartica_60 <- leafletCRS(crsClass = "L.Proj.CRS", 
                              code = "EPSG:3031", 
                              proj4def = "+proj=stere +lat_0=-90 +lat_ts=-71 +lon_0=-60 +k=1 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs", 
                              resolutions = resolutions,  
                              origin = c(-3.369955099203E7, 3.369955101703E7), 
                              bounds = list(c(-extent, -extent), c(extent, extent))
)


ui <- fluidPage(
  tags$head(tags$style(".btn-default {display: block;}")),
  h4("Leaflet Sidebar Plugin"),
  splitLayout(cellWidths = c("20%", "80%"),
              tagList(
                actionButton("open", "Open Sidebar"),
                actionButton("close", "Close Sidebar"),
                actionButton("clear", "Clear Sidebar"),
                actionButton("rotate", "Rotate Map"),
                
                verbatimTextOutput("whichtab")
              ),
              tagList(
                sidebar_tabs(id = "mysidebarid",
                             list(icon("car"), icon("user"), icon("envelope")),
                             sidebar_pane(
                               title = "home", id = "home_id", icon = icon("home"),

                             ),
                             sidebar_pane(
                               title = "profile", id = "profile_id", icon = icon("wrench"),

                                 ),
                             sidebar_pane(
                               title = "messages", id = "messages_id",
                               icon = icon("person", verify_fa = FALSE),

                                         )
                ),
                leafletOutput("map", height = "700px")
              )
  )
)

server <- function(input, output, session) {
  output$map <- renderLeaflet({
      leaflet(options = leafletOptions(crs = crsAntartica,   minZoom = 3, maxZoom = 13)) %>%
      addPolygons(data = antarctica, color = "black", weight = 2, fillColor = "lightgrey") %>% 
      setView(lng = -40, lat = -75, zoom = 4)  %>%
        addSidebar(
        id = "mysidebarid",
        options = list(position = "left")
      )
  })
  output$whichtab <- renderPrint({
    paste0(req(input$mysidebarid), " is open")
  })
  


  observeEvent(input$open, {
    leafletProxy("map", session) %>%
      openSidebar(sample(c("home_id","profile_id","messages_id"), 1))
  })
  observeEvent(input$close, {
    leafletProxy("map", session) %>%
      closeSidebar()
  })
  observeEvent(input$clear, {
    leafletProxy("map", session) %>%
      removeSidebar()
  })
  
  observeEvent(input$rotate, {
    
    output$map <- renderLeaflet({
    leaflet(options = leafletOptions(crs = crsAntartica_60,   minZoom = 3, maxZoom = 13)) %>%
        addPolygons(data = antarctica, color = "black", weight = 2, fillColor = "lightgrey") %>%
        setView(lng = -40, lat = -75, zoom = 4)
    })
    
  })
  
  
}
shinyApp(ui, server))
```

**Comment by trafficonese** [comment]
I just pushed [b0d619f](https://github.com/trafficonese/leaflet.extras2/commit/b0d619f0457b070686de5e3c9caf63da7cd529a4) which makes it possible to add a new sidebar, but you will have to create another `sidebar_tabs` with another `id` (which is hidden initially), as you create a new leaflet map that doesn't know that there was another sidebar in the other map..

Here is a working solution. I hope this helps.
```
## Libs #############
library(sf)
library(sp)
library(shiny)
library(leaflet)
library(leaflet.extras2)
library(rnaturalearth)
## data ############
world <- ne_countries(scale = "medium", returnclass = "sf")
antarctica <- world[world$name == "Antarctica", ]

resolutions <- c(238810.813354,119405.406677, 59702.7033384999, 29851.3516692501,14925.675834625,
                 7462.83791731252,3731.41895865639, 1865.70947932806,932.854739664032,
                 466.427369832148, 233.213684916074, 116.60684245803701, 58.30342122888621,
                 29.151710614575396, 14.5758553072877, 7.28792765351156, 3.64396382688807,
                 1.82198191331174, 0.910990956788164, 0.45549547826179, 0.227747739130895,
                 0.113873869697739, 0.05693693484887, 0.028468467424435)
extent<-3.0635955947272874e+07

crsAntartica <- leafletCRS(crsClass = "L.Proj.CRS", 
                           code = "EPSG:3031", 
                           proj4def = "+proj=stere +lat_0=-90 +lat_ts=-71 +lon_0=0 +k=1 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs", 
                           resolutions = resolutions,  
                           origin = c(-3.369955099203E7, 3.369955101703E7), 
                           bounds = list(c(-extent, -extent), c(extent, extent))
)

crsAntartica_60 <- leafletCRS(crsClass = "L.Proj.CRS", 
                              code = "EPSG:3031", 
                              proj4def = "+proj=stere +lat_0=-90 +lat_ts=-71 +lon_0=-60 +k=1 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs", 
                              resolutions = resolutions,  
                              origin = c(-3.369955099203E7, 3.369955101703E7), 
                              bounds = list(c(-extent, -extent), c(extent, extent))
)

## ui ############
ui <- fluidPage(
  tags$head(tags$style(".btn-default {display: block;}")),
  h4("Leaflet Sidebar Plugin"),
  div(style="display:none", 
      sidebar_tabs(id = "mysidebarid_2map",
                   list(icon("car"), icon("user"), icon("envelope")),
                   sidebar_pane(
                     title = "home", id = "home_id", icon = icon("home"),
                     
                   ),
                   sidebar_pane(
                     title = "profile", id = "profile_id", icon = icon("wrench"),
                     
                   ),
                   sidebar_pane(
                     title = "messages", id = "messages_id",
                     icon = icon("person", verify_fa = FALSE),
                     
                   )
  )),
  splitLayout(cellWidths = c("20%", "80%"),
              tagList(
                actionButton("open", "Open Sidebar"),
                actionButton("close", "Close Sidebar"),
                actionButton("clear", "Clear Sidebar"),
                actionButton("rotate", "Rotate Map"),
                verbatimTextOutput("whichtab"),
                verbatimTextOutput("whichtab2")
              ),
              tagList(
                sidebar_tabs(id = "mysidebarid",
                             list(icon("car"), icon("user"), icon("envelope")),
                             sidebar_pane(
                               title = "home", id = "home_id", icon = icon("home"),
                               
                             ),
                             sidebar_pane(
                               title = "profile", id = "profile_id", icon = icon("wrench"),
                               
                             ),
                             sidebar_pane(
                               title = "messages", id = "messages_id",
                               icon = icon("person", verify_fa = FALSE),
                               
                             )
                ),
                leafletOutput("map", height = "700px")
              )
  )
)

## server ############
server <- function(input, output, session) {
  output$map <- renderLeaflet({
    leaflet(options = leafletOptions(crs = crsAntartica,   minZoom = 3, maxZoom = 13)) %>%
      addPolygons(data = antarctica, color = "black", weight = 2, fillColor = "lightgrey") %>% 
      setView(lng = -40, lat = -75, zoom = 4) %>%
      addSidebar(
        id = "mysidebarid",
        options = list(position = "left")
      )
  })
  output$whichtab <- renderPrint({
    paste0(req(input$mysidebarid), " is open for `mysidebarid`")
  })
  output$whichtab2 <- renderPrint({
    paste0(req(input$mysidebarid_2map), " is open for `mysidebarid_2map`")
  })
  
  
  observeEvent(input$open, {
    leafletProxy("map", session) %>%
      openSidebar(sample(c("home_id","profile_id","messages_id"), 1))
  })
  observeEvent(input$close, {
    leafletProxy("map", session) %>%
      closeSidebar()
  })
  observeEvent(input$clear, {
    leafletProxy("map", session) %>%
      removeSidebar(sidebar_id = "mysidebarid")
  })
  
  observeEvent(input$rotate, {
    output$map <- renderLeaflet({
      leaflet(options = leafletOptions(crs = crsAntartica_60,   minZoom = 3, maxZoom = 13)) %>%
        addPolygons(data = antarctica, color = "black", weight = 2, fillColor = "lightgrey") %>%
        setView(lng = -40, lat = -75, zoom = 4) %>% 
        removeSidebar() %>% 
        addSidebar(
          id = "mysidebarid_2map",
          options = list(position = "left"))
    })
  })
}
shinyApp(ui, server)
```

**Comment by Daphnisd** [comment]
Thanks for that workaround, which i think could work for me. However I have difficulty removing the previous sidebar. In the example, when you open a tab and then press rotate the new sidebar is added on top of the old one, without removing the old one. First pressing Clear Sidebar and then rotate does work. So I thought the following workaround would work, but it doesn't.

```r
  observeEvent(input$rotate, {
    leafletProxy("map", session) %>%
      removeSidebar(sidebar_id = "mysidebarid")
    
    output$map <- renderLeaflet({
      leaflet(options = leafletOptions(crs = crsAntartica_60,   minZoom = 3, maxZoom = 13)) %>%
        addPolygons(data = antarctica, color = "black", weight = 2, fillColor = "lightgrey") %>%
        setView(lng = -40, lat = -75, zoom = 4) %>% 
        addSidebar(
          id = "mysidebarid_2map",
          options = list(position = "left"))
    })
  })
```

After rotating, sometimes I can't move the map anymore using the mouse while moving the map with the arrows on the keyboard still works.

**Comment by trafficonese** [comment]
I think there is a problem with this approach in leaflet. If you just try out this app and zoom in/out, then click "Rotate Map" and then zoom in/out again you will see this error in the browser console:

> leaflet.js:5 Uncaught TypeError: Cannot read properties of undefined (reading '_leaflet_pos')

```
library(shiny)
library(leaflet)
library(leaflet.extras2)
ui <- fluidPage(
  actionButton("rotate", "Rotate Map"),
  leafletOutput("map", height = "700px")
)
server <- function(input, output, session) {
  output$map <- renderLeaflet({
    leaflet() %>%
      setView(lng = -40, lat = -75, zoom = 4)
  })
  observeEvent(input$rotate, {
    output$map <- renderLeaflet({
      leaflet() %>%
        setView(lng = -40, lat = -75, zoom = 4) 
    })
  })
}
shinyApp(ui, server)
```
--------------

So I think the solution to the problem would be to have 2 separate maps and 2 separate sidebars and you just hide/show the maps.. Here is an example using `shinyjs`, where I also store which map and sidebar is active using 2 `reactiveVal`.

But there is still something wrong as the new sidebar is hiding the zoom buttons. I will look into it.
But could this be a solution for you?

```
## Libs #############
library(sf)
library(shiny)
library(shinyjs)
library(leaflet)
library(leaflet.extras2)
library(rnaturalearth)
## data ############
world <- ne_countries(scale = "medium", returnclass = "sf")
antarctica <- world[world$name == "Antarctica", ]

resolutions <- c(238810.813354,119405.406677, 59702.7033384999, 29851.3516692501,14925.675834625,
                 7462.83791731252,3731.41895865639, 1865.70947932806,932.854739664032,
                 466.427369832148, 233.213684916074, 116.60684245803701, 58.30342122888621,
                 29.151710614575396, 14.5758553072877, 7.28792765351156, 3.64396382688807,
                 1.82198191331174, 0.910990956788164, 0.45549547826179, 0.227747739130895,
                 0.113873869697739, 0.05693693484887, 0.028468467424435)
extent<-3.0635955947272874e+07

crsAntartica <- leafletCRS(crsClass = "L.Proj.CRS", 
                           code = "EPSG:3031", 
                           proj4def = "+proj=stere +lat_0=-90 +lat_ts=-71 +lon_0=0 +k=1 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs", 
                           resolutions = resolutions,  
                           origin = c(-3.369955099203E7, 3.369955101703E7), 
                           bounds = list(c(-extent, -extent), c(extent, extent))
)

crsAntartica_60 <- leafletCRS(crsClass = "L.Proj.CRS", 
                              code = "EPSG:3031", 
                              proj4def = "+proj=stere +lat_0=-90 +lat_ts=-71 +lon_0=-60 +k=1 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs", 
                              resolutions = resolutions,  
                              origin = c(-3.369955099203E7, 3.369955101703E7), 
                              bounds = list(c(-extent, -extent), c(extent, extent))
)

## ui ############
ui <- fluidPage(
  tags$head(tags$style(".btn-default {display: block;}")),
  useShinyjs(),
  h4("Leaflet Sidebar Plugin"),
  div(style="display:none", 
      sidebar_tabs(id = "mysidebarid_2map",
                   list(icon("car"), icon("user"), icon("envelope")),
                   sidebar_pane(
                     title = "home", id = "home_id", icon = icon("home"),
                     
                   ),
                   sidebar_pane(
                     title = "profile", id = "profile_id", icon = icon("wrench"),
                     
                   ),
                   sidebar_pane(
                     title = "messages", id = "messages_id",
                     icon = icon("person", verify_fa = FALSE),
                     
                   )
  )),
  splitLayout(cellWidths = c("20%", "80%"),
              tagList(
                actionButton("open", "Open Sidebar"),
                actionButton("close", "Close Sidebar"),
                actionButton("clear", "Clear Sidebar"),
                actionButton("rotate", "Rotate Map"),
                actionButton("debug", "debug"),
                verbatimTextOutput("whichtab"),
                verbatimTextOutput("whichtab2"),
                verbatimTextOutput("sidebarid")
              ),
              tagList(
                sidebar_tabs(id = "mysidebarid",
                             list(icon("car"), icon("user"), icon("envelope")),
                             sidebar_pane(
                               title = "home", id = "home_id", icon = icon("home"),
                               
                             ),
                             sidebar_pane(
                               title = "profile", id = "profile_id", icon = icon("wrench"),
                               
                             ),
                             sidebar_pane(
                               title = "messages", id = "messages_id",
                               icon = icon("person", verify_fa = FALSE),
                               
                             )
                ),
                leafletOutput("map", height = "700px"),
                leafletOutput("map2", height = "700px")
              )
  )
)

## server ############
server <- function(input, output, session) {
  output$map <- renderLeaflet({
    leaflet(options = leafletOptions(crs = crsAntartica,   minZoom = 3, maxZoom = 13)) %>%
      addPolygons(data = antarctica, color = "black", weight = 2, fillColor = "lightgrey") %>% 
      setView(lng = -40, lat = -75, zoom = 4) %>%
      addSidebar(
        id = "mysidebarid",
        options = list(position = "left")
      )
  })
  output$whichtab <- renderPrint({
    paste0(req(input$mysidebarid), " is open for `mysidebarid`")
  })
  output$whichtab2 <- renderPrint({
    paste0(req(input$mysidebarid_2map), " is open for `mysidebarid_2map`")
  })
  output$sidebarid <- renderPrint({
    sidebarid()
  })
  
  sidebarid <- reactiveVal("mysidebarid")
  mapid <- reactiveVal("map")
  
  observeEvent(input$debug, {
    browser()
  })
  observeEvent(input$open, {
    leafletProxy(mapid(), session) %>%
      openSidebar(sample(c("home_id","profile_id","messages_id"), 1), sidebarid())
  })
  observeEvent(input$close, {
    leafletProxy(mapid(), session) %>%
      closeSidebar(sidebar_id = sidebarid())
  })
  observeEvent(input$clear, {
    leafletProxy(mapid(), session) %>%
      removeSidebar(sidebar_id = sidebarid())
  })
  
  observeEvent(input$rotate, {
    leafletProxy("map", session) %>%
      removeSidebar(sidebar_id = "mysidebarid")
    
    shinyjs::hide("map")
    sidebarid("mysidebarid_2map")
    mapid("map2")
        
    output$map2 <- renderLeaflet({
      leaflet(options = leafletOptions(crs = crsAntartica_60,   minZoom = 3, maxZoom = 13)) %>%
        addPolygons(data = antarctica, color = "black", weight = 2, fillColor = "lightgrey") %>%
        setView(lng = -40, lat = -75, zoom = 4) %>% 
        addSidebar(
          id = "mysidebarid_2map",
          options = list(position = "left"))
    })
  })
  
  
}
shinyApp(ui, server)
```

**Comment by trafficonese** [comment]
Interestingly when you click `Clear Sidebar` first and then `Rotate Map`, the sidebar looks correct and doesnt hide the zoom-buttons..

**Comment by trafficonese** [comment]
I just pushed [96298c7](https://github.com/trafficonese/leaflet.extras2/commit/96298c746b1c65c74247ae2f5c5a362d2ae4d914) which should fix the CSS-bugs

**Comment by Daphnisd** [comment]
Thanks for that. This approach would work for me.  However ideally a user would be able to switch between the rotations and go back and forth between them. Currently witching to a new projection works well, but I have some problems when I go back to the previous one. I tried several approaches but I'm likely missing something? 


'''r
## Libs #############
library(sf)
library(shiny)
library(shinyjs)
library(leaflet)
library(leaflet.extras2)
library(rnaturalearth)
## data ############
world <- ne_countries(scale = "medium", returnclass = "sf")
antarctica <- world[world$name == "Antarctica", ]

resolutions <- c(238810.813354,119405.406677, 59702.7033384999, 29851.3516692501,14925.675834625,
                 7462.83791731252,3731.41895865639, 1865.70947932806,932.854739664032,
                 466.427369832148, 233.213684916074, 116.60684245803701, 58.30342122888621,
                 29.151710614575396, 14.5758553072877, 7.28792765351156, 3.64396382688807,
                 1.82198191331174, 0.910990956788164, 0.45549547826179, 0.227747739130895,
                 0.113873869697739, 0.05693693484887, 0.028468467424435)
extent<-3.0635955947272874e+07

crsAntartica <- leafletCRS(crsClass = "L.Proj.CRS", 
                           code = "EPSG:3031", 
                           proj4def = "+proj=stere +lat_0=-90 +lat_ts=-71 +lon_0=0 +k=1 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs", 
                           resolutions = resolutions,  
                           origin = c(-3.369955099203E7, 3.369955101703E7), 
                           bounds = list(c(-extent, -extent), c(extent, extent))
)

crsAntartica_ap <- leafletCRS(crsClass = "L.Proj.CRS", 
                              code = "EPSG:3031", 
                              proj4def = "+proj=stere +lat_0=-90 +lat_ts=-71 +lon_0=-60 +k=1 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs", 
                              resolutions = resolutions,  
                              origin = c(-3.369955099203E7, 3.369955101703E7), 
                              bounds = list(c(-extent, -extent), c(extent, extent))
)

crsAntartica_rs <- leafletCRS(crsClass = "L.Proj.CRS", 
                              code = "EPSG:3031", 
                              proj4def = "+proj=stere +lat_0=-90 +lat_ts=-71 +lon_0=-170 +k=1 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs", 
                              resolutions = resolutions,  
                              origin = c(-3.369955099203E7, 3.369955101703E7), 
                              bounds = list(c(-extent, -extent), c(extent, extent))
)

myrotations <- c('Standard' = 0,
                 'Antarctic peninsula' = -60,
                 'Ross sea' = -170)

## ui ############
ui <- fluidPage(
  tags$head(tags$style(".btn-default {display: block;}")),
  useShinyjs(),
  h4("Leaflet Sidebar Plugin"),
  div(style="display:none", 
      sidebar_tabs(id = "mysidebarid_rs",
                   list(icon("car"), icon("user"), icon("envelope")),
                   sidebar_pane(
                     title = "ross sea", id = "home_id", icon = icon("home"),
                     
                   ),
                   sidebar_pane(
                     title = "profile", id = "profile_id", icon = icon("wrench"),
                     
                   ),
                   sidebar_pane(
                     title = "messages", id = "messages_id",
                     icon = icon("person", verify_fa = FALSE),
                     
                   )
      ),
      sidebar_tabs(id = "mysidebarid_ap",
                   list(icon("car"), icon("user"), icon("envelope")),
                   sidebar_pane(
                     title = "Antarctic peninsula", id = "home_id", icon = icon("home"),
                     
                   ),
                   sidebar_pane(
                     title = "profile", id = "profile_id", icon = icon("wrench"),
                     
                   ),
                   sidebar_pane(
                     title = "messages", id = "messages_id",
                     icon = icon("person", verify_fa = FALSE),
                     
                   )
      )),
  splitLayout(cellWidths = c("20%", "80%"),
              tagList(
                actionButton("open", "Open Sidebar"),
                actionButton("close", "Close Sidebar"),
                actionButton("clear", "Clear Sidebar"),
                radioButtons("rotation", NULL, choices = myrotations, selected = myrotations[1]),
                actionButton("debug", "debug"),
                verbatimTextOutput("whichtab"),
                verbatimTextOutput("whichtab2"),
                verbatimTextOutput("whichtab3"),
                verbatimTextOutput("sidebarid")
              ),
              tagList(
                sidebar_tabs(id = "mysidebarid",
                             list(icon("car"), icon("user"), icon("envelope")),
                             sidebar_pane(
                               title = "Standard", id = "home_id", icon = icon("home"),
                               
                             ),
                             sidebar_pane(
                               title = "profile", id = "profile_id", icon = icon("wrench"),
                               
                             ),
                             sidebar_pane(
                               title = "messages", id = "messages_id",
                               icon = icon("person", verify_fa = FALSE),
                               
                             )
                ),
                leafletOutput("map", height = "700px"),
                leafletOutput("map_ap", height = "700px"),
                leafletOutput("map_rs", height = "700px")
              )
  )
)

## server ############
server <- function(input, output, session) {
  output$map <- renderLeaflet({
    leaflet(options = leafletOptions(crs = crsAntartica,   minZoom = 3, maxZoom = 13)) %>%
      addPolygons(data = antarctica, color = "black", weight = 2, fillColor = "lightgrey") %>% 
      setView(lng = -40, lat = -75, zoom = 4) %>%
      addSidebar(
        id = "mysidebarid",
        options = list(position = "left")
      )
  })
  output$whichtab <- renderPrint({
    paste0(req(input$mysidebarid), " is open for `mysidebarid`")
  })
  output$whichtab2 <- renderPrint({
    paste0(req(input$mysidebarid_ap), " is open for `mysidebarid_ap`")
  })
  output$whichtab3 <- renderPrint({
    paste0(req(input$mysidebarid_rs), " is open for `mysidebarid_rs`")
  })
  
  output$sidebarid <- renderPrint({
    sidebarid()
  })
  
  sidebarid <- reactiveVal("mysidebarid")
  mapid <- reactiveVal("map")
  map_ap_loaded <- reactiveVal(FALSE)
  map_rs_loaded <- reactiveVal(FALSE)
  
  observeEvent(input$debug, {
    browser()
  })
  observeEvent(input$open, {
    leafletProxy(mapid(), session) %>%
      openSidebar(sample(c("home_id","profile_id","messages_id"), 1), sidebarid())
  })
  observeEvent(input$close, {
    leafletProxy(mapid(), session) %>%
      closeSidebar(sidebar_id = sidebarid())
  })
  observeEvent(input$clear, {
    leafletProxy(mapid(), session) %>%
      removeSidebar(sidebar_id = sidebarid())
  })
  
  observeEvent(input$rotation, ignoreInit = T, {
    # leafletProxy(mapid(), session) %>%
    #   removeSidebar(sidebar_id = sidebarid())
    
    if(input$rotation == '0'){
      shinyjs::hide(mapid())
      mapid("map")
      sidebarid("mysidebarid")
      
      # leafletProxy(mapid(), session) %>%
      #   addSidebar(
      #     id = sidebarid(),
      #     options = list(position = "left"))
      
      shinyjs::show(mapid())

    }
    if(input$rotation == '-60'){
      shinyjs::hide(mapid())
      mapid("map_ap")
      sidebarid("mysidebarid_ap")
      
      if(!map_ap_loaded()) {
      output$map_ap <- renderLeaflet({
        leaflet(options = leafletOptions(crs = crsAntartica_ap,   minZoom = 3, maxZoom = 13)) %>%
          addPolygons(data = antarctica, color = "black", weight = 2, fillColor = "lightgrey") %>%
          setView(lng = -40, lat = -75, zoom = 4) %>% 
          addSidebar(
            id = sidebarid(),
            options = list(position = "left"))
      })
      map_ap_loaded(TRUE)
      } else {
        
        # leafletProxy(mapid(), session) %>%
        #   addSidebar(
        #     id = sidebarid(),
        #     options = list(position = "left"))
        
        shinyjs::show(mapid())
        
      }
      
    }
    if(input$rotation == '-170'){
      shinyjs::hide(mapid())
      mapid("map_rs")
      sidebarid("mysidebarid_rs")
      
      if(!map_rs_loaded()) {
      output$map_rs <- renderLeaflet({
        leaflet(options = leafletOptions(crs = crsAntartica_rs,   minZoom = 3, maxZoom = 13)) %>%
          addPolygons(data = antarctica, color = "black", weight = 2, fillColor = "lightgrey") %>%
          setView(lng = -40, lat = -75, zoom = 4) %>% 
          addSidebar(
            id = sidebarid(),
            options = list(position = "left"))
      }) 
      map_rs_loaded(TRUE )} else {
        # leafletProxy(mapid(), session) %>%
        #   addSidebar(
        #     id = sidebarid(),
        #     options = list(position = "left"))
        
        shinyjs::show(mapid())
        
      }
    }
  })
}
shinyApp(ui, server)
'''

**Comment by Daphnisd** [comment]
I now realize that I can't use the same id's for input selectors across the different sidebars. I guess I can work around that using uiOutput, but it's probably best I just force users to decide on a map rotation before the map loads.

**Comment by trafficonese** [comment]
Yes I guess that would be best. I also dont have much knowledge in changing projections in leaflet or everytime I had to deal with it, it was painful.

**Comment by Daphnisd** [comment]
Thanks again for your help!

**Comment by trafficonese** [comment]
You're welcome, feel free to close the issue :)
