### ISSUE TITLE
WMS server error. Invalid layer(s) given in the LAYERS parameter.

### ISSUE THREAD

**Issue by p-schaefer** [trafficonese/leaflet.extras2#73]
I'm having an issue retrieving feature information from a WMS layer, and I don't know if its the source thats the issue, or the package. The error I'm getting is: `msWMSLoadGetMapParams(): WMS server error. Invalid layer(s) given in the LAYERS parameter. A layer might be disabled for this request. Check wms/ows_enable_request settings.`

![image](https://github.com/user-attachments/assets/6ffe43f2-028a-45f0-b814-93c971d5f2ca)

```r
library(leaflet)
library(leaflet.extras2)

leaflet() %>% 
  setView(lng = -79.6, lat = 43.6, zoom = 9) %>% 
  addProviderTiles(providers$OpenStreetMap.Mapnik) %>% 
  addWMS(baseUrl = "https://maps.geogratis.gc.ca/wms/hydro_network_en?",
              layers = "nhn:nhn:drainageareas:nhnda", 
              options = WMSTileOptions(format = "image/png", transparent = T)
  ) %>% 
  addWMS(baseUrl = "https://maps.geogratis.gc.ca/wms/hydro_network_en?",
              layers = "nhn:nhn:drainageareas:nhnda:names", 
              options = WMSTileOptions(format = "image/png", 
                                       transparent = T,
                                       info_format = "text/html",
                                       interactive = TRUE)
  )

```

**Comment by trafficonese** [comment]
This looks pretty much loke the layer is disabled for GetFeature requests.. Do you have control over the source layer?

Did you check out this?
https://gis.stackexchange.com/questions/65074/mswmsgetcapabilities-wms-server-error-wms-request-not-enabled

**Comment by p-schaefer** [comment]
Thanks @trafficonese. No, I do not have control over the layer. The source is here:

https://open.canada.ca/data/en/dataset/a4b190fe-e090-4e6d-881e-b87956c07977

is this something I should submit a bug report to the source, or something I can fix on my end?

**Comment by trafficonese** [comment]
I am not entirely sure, I think the problem is on the source side, or they just deactivated the `GetFeature` option for this layer.

**Comment by p-schaefer** [comment]
Confirmed, error was in the source. They are working on fixing. Thanks.
