### ISSUE TITLE
Feature Request : add L.Control.Rose plugin

### ISSUE THREAD

**Issue by MaelTheuliere** [trafficonese/leaflet.extras2#8]
I see no alternative to add north arrow to a leaflet map. 
This feature is asked by users of our maps, especially for png export.
Link to the plugin https://github.com/bradhamson/L.Control.Rose

**Comment by tim-salabim** [comment]
@MaelTheuliere you could try to use [`leafem::addLogo`](https://github.com/r-spatial/leafem#addlogo) for this porpose (sorry that I didn't mention it in the other issue) if you can find a suitable north_arrow.png

**Comment by tim-salabim** [comment]
Here's a reprex:

``` r
library(leafem)
#> Warning: replacing previous import 'vctrs::data_frame' by 'tibble::data_frame'
#> when loading 'dplyr'
library(leaflet)
## default position is topleft next to zoom control
img <- "https://cdn.pixabay.com/photo/2013/07/12/17/54/arrow-152596_960_720.png"

leaflet() %>% 
  addTiles() %>% 
  addLogo(img)
```

![](https://i.imgur.com/dHMSEZy.png)

<sup>Created on 2020-11-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by trafficonese** [comment]
Hey @MaelTheuliere I think that `leafem :: addLogo` works well for this task and also allows you to define your custom image while the plugin only offers ~7 different .svg files.

On the other hand, this plugin should be pretty easy to implement. If you want to try it out, I would of course be happy about a PR.

**Comment by MaelTheuliere** [comment]
Thanks @trafficonese and @tim-salabim. I think `leafem :: addLogo` will do the job ! If I find some time to make a PR with `L.Control.Rose`, I will let you know.
